default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development
  username: admin
  password: adminpass
  host: db

test:
  <<: *default
  database: app_test
  username: admin
  password: adminpass
  host: db

production:
  <<: *default
  database: <%= ENV['MINIBLOG_DB_DATABASE'] %>
  username: <%= ENV['MINIBLOG_DB_USERNAME'] %>
  password: <%= ENV['MINIBLOG_DB_PASSWORD'] %>
  host: <%= ENV['MINIBLOG_DB_HOST'] %>
